// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.211
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CommentTranslatorChina
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidCommentTranslatorPackageString = "2e2206c4-ab10-44d9-a016-aedfe6a8975f";
        public const string guidCommentTranslatorPackageCmdSetString = "284ee4d1-edc6-4ed0-bf84-d45aeebf593c";
        public const string CMDSETID_CssEdGrpString = "a764e896-518d-11d2-9a89-00c04f79efc3";
        public const string CMDSETID_HtmEdGrpString = "d7e8c5e1-bdb8-11d0-9c88-0000f8040a53";
        public const string GuidVisualStudioCSSWindowContextMenuString = "a764e896-518d-11d2-9a89-00c04f79efc3";
        public const string GuidVisualStudioCSSDocumentContextMenuString = "64da400e-b4ad-4d67-aa92-4b7acb01ecd5";
        public const string GuidVisualStudioHTMLWindowContextMenuString = "d7e8c5e1-bdb8-11d0-9c88-0000f8040a53";
        public const string GuidVisualStudioHTMLDocumentContextMenuString = "78f03954-2fb8-4087-8ce7-59d71710b3bb";
        public const string GuidVisualStudioJSONDocumentContextMenuString = "f718ca06-cf4f-4a0c-9106-e79e9ee5e7cd";
        public const string XamlEditorWindowsString = "4c87b692-1202-46aa-b64c-ef01faec53da";
        public const string jsEditorCommandSetString = "d309f791-903f-11d0-9efc-00a0c911004f";
        public const string guidImagesString = "7739b59e-19f6-420e-8597-8af69c377a6a";
        public static Guid guidCommentTranslatorPackage = new Guid(guidCommentTranslatorPackageString);
        public static Guid guidCommentTranslatorPackageCmdSet = new Guid(guidCommentTranslatorPackageCmdSetString);
        public static Guid CMDSETID_CssEdGrp = new Guid(CMDSETID_CssEdGrpString);
        public static Guid CMDSETID_HtmEdGrp = new Guid(CMDSETID_HtmEdGrpString);
        public static Guid GuidVisualStudioCSSWindowContextMenu = new Guid(GuidVisualStudioCSSWindowContextMenuString);
        public static Guid GuidVisualStudioCSSDocumentContextMenu = new Guid(GuidVisualStudioCSSDocumentContextMenuString);
        public static Guid GuidVisualStudioHTMLWindowContextMenu = new Guid(GuidVisualStudioHTMLWindowContextMenuString);
        public static Guid GuidVisualStudioHTMLDocumentContextMenu = new Guid(GuidVisualStudioHTMLDocumentContextMenuString);
        public static Guid GuidVisualStudioJSONDocumentContextMenu = new Guid(GuidVisualStudioJSONDocumentContextMenuString);
        public static Guid XamlEditorWindows = new Guid(XamlEditorWindowsString);
        public static Guid jsEditorCommandSet = new Guid(jsEditorCommandSetString);
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int MyMenuToolGroup = 0x1021;
        public const int CommentTranslatorId = 0x0100;
        public const int ToggleAutoTranslatorId = 0x0101;
        public const int GetTKKId = 0x0111;
        public const int IDM_CTX_SOURCE = 0x0102;
        public const int IDMX_HTM_SOURCE_BASIC = 0x0032;
        public const int IDMX_HTM_SOURCE_HTML = 0x0033;
        public const int IDMX_HTM_SOURCE_SCRIPT = 0x0034;
        public const int IDMX_HTM_SOURCE_ASPX = 0x0035;
        public const int IDMX_HTM_SOURCE_ASAX = 0x003B;
        public const int IDMX_HTM_SOURCE_ASPX_CODE = 0x0036;
        public const int IDMX_HTM_SOURCE_ASAX_CODE = 0x003C;
        public const int IDMX_HTM_SOURCE_ASPX_CODE_VB = 0x0037;
        public const int IDMX_HTM_SOURCE_ASAX_CODE_VB = 0x003D;
        public const int IDMX_HTM_SOURCE_ASMX_CODE = 0x0038;
        public const int IDMX_HTM_SOURCE_ASMX_CODE_VB = 0x0039;
        public const int IDVisualStudioCSSWindowContextMenu = 0x0102;
        public const int IDVisualStudioCSSDocumentContextMenu = 0x0002;
        public const int IDVisualStudioASPXWindowContextMenu = 0x0035;
        public const int IDVisualStudioASPXCodeWindowContextMenu = 0x0036;
        public const int IDVisualStudioHTMLWindowContextMenu = 0x0033;
        public const int IDVisualStudioScriptWindowContextMenu = 0x0034;
        public const int IDVisualStudioHTMLDocumentContextMenu = 0x0001;
        public const int IDVisualStudioJSONDocumentContextMenu = 0x0003;
        public const int IDMX_XAML_SOURCE_BASIC = 0x0103;
        public const int jsContextMenu = 0x040D;
        public const int bmpPic1 = 0x0001;
    }
}
