// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.211
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CommentTranslatorChina
{
    static class Vsix
    {
        public const string Id = "9EE09180-C729-4369-9E1B-4FEAB1C3C0D0";
        public const string Name = "Comment Translator China";
        public const string Description = @"Extension of visual studio that automatic translate comment in you open file.";
        public const string Language = "zh-CN";
        public const string Version = "1.1";
        public const string Author = "Jia";
        public const string Tags = "translate, comment";
    }
}
